# Generated by Django 5.1.1 on 2024-10-13 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('INN', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'app_company',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(max_length=256, verbose_name='Tovar')),
                ('transport_service', models.CharField(max_length=256, verbose_name='Transport usluga')),
                ('contract_no', models.CharField(max_length=256, verbose_name='Kontrakt raqami')),
                ('date_recorded', models.DateField(verbose_name='Qayd etilgan sana')),
                ('seller', models.CharField(max_length=256, verbose_name='sotuvchi')),
                ('carrier', models.CharField(max_length=256, verbose_name='tashuvchi')),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='qabul qiluvchi')),
            ],
            options={
                'db_table': 'app_contract',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customs_mode', models.CharField(choices=[('IM70', 'IM 70'), ('IM40', 'IM 40'), ('ND40', 'ND 40'), ('IM74', 'IM 74'), ('EK10', 'EK 10')], max_length=10)),
                ('number_gtd', models.CharField(max_length=256, verbose_name='nomer gtd')),
                ('reference_gtd', models.CharField(max_length=256)),
                ('date_recorded', models.DateField(verbose_name='qayd etilgan sana')),
                ('sender', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('factor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('BOSILDI', 'BOSILDI'), ('BOSILMADI', 'BOSILMADI')], max_length=15)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
            options={
                'db_table': 'app_declaration',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Dosmotr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_number', models.CharField(max_length=256, verbose_name='avtotransport raqami')),
                ('product', models.CharField(max_length=256)),
                ('weight', models.CharField(max_length=256, verbose_name="og'irligi")),
                ('arrived_date', models.DateField(verbose_name='yuk kelgan sana')),
                ('leaving_date', models.DateField(verbose_name='yuk ombordan chiqib ketgan sana')),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
            options={
                'db_table': 'app_dosmotr',
                'ordering': ['-updated_at'],
            },
        ),
    ]
