# Generated by Django 5.1.1 on 2024-10-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='customs_mode',
            field=models.CharField(choices=[('IM70', 'IM 70'), ('IM40', 'IM 40'), ('ND40', 'ND 40'), ('IM74', 'IM 74'), ('EK10', 'EK 10'), ('VABOSHQALAR', 'VA BOSHQALAR')], max_length=20, verbose_name='Rejimi'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='date_recorded',
            field=models.DateField(verbose_name='Qayd etilgan sana'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='number_gtd',
            field=models.CharField(max_length=256, verbose_name='Nomer gtd'),
        ),
    ]
